/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 07-sep-2020 07:24:17 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   categoria CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   ciudad CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   cliente CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   cliente_direccion CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   cliente_tarjetacredito CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   costo_envio CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   direccion CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   inventario CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   pago CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   pago_pse CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   pago_tarjetacredito CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   parametro CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   pedido_cliente CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   producto CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   producto_pedidocliente CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   proveedor CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   tarjeta_credito CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  categoria
(
	K_IDCATEGORIA NUMBER(10) NOT NULL,    -- Identificador de la categoría
	N_NOMBRE VARCHAR(50) NOT NULL,    -- Nombre de la categoría
	K_IDCATEGORIAPADRE NUMBER(10) NULL    -- Identificador de la categoría padre. Usado para especificar que una categoría es una subcategoría de otra
)
;

CREATE TABLE  ciudad
(
	K_IDCIUDAD NUMBER(10) NOT NULL,    -- Identificador de la ciudad
	N_NOMBRE VARCHAR(50) NOT NULL    -- Nombre de la ciudad
)
;

CREATE TABLE  cliente
(
	K_IDCLIENTE NUMBER(8) NOT NULL,    -- Respresenta el identificador de cada uno de los clientes registrados en el sistema.
	I_TIPOIDENT VARCHAR(50) NOT NULL,    -- Tipo de identificación
	K_NUMIDENT NUMBER(15) NOT NULL,    -- Número de identificación propio de cada persona DNI
	N_NOMBRE VARCHAR(100) NOT NULL,    -- Nombre del cliente
	F_FECHANACIMIENTO DATE NOT NULL,    -- Fecha de nacimiento del cliente, a partir de la cual se calcula su edad
	I_GENERO VARCHAR(2) NOT NULL,    -- Género con el cual se identifica del cliente
	O_EMAIL VARCHAR(100) NOT NULL,    -- Correo electrónico perteneciente al cliente y a través del cual se le brindará información de su cuenta
	N_NOMBREUSUARIO VARCHAR(50) NOT NULL,
	K_IDCIUDAD NUMBER(10) NULL
)
;

CREATE TABLE  cliente_direccion
(
	K_IDCLIENTE NUMBER(10) NOT NULL,    -- Número único de identificación del cliente
	K_IDDIRECCION NUMBER(10) NOT NULL,    -- Identificador único de la dirección de domicilio
	I_ESTADO VARCHAR(8) NOT NULL    -- Estado de la dirección del cliente. Activo si está disponible. Inactivo si no lo está. Se pasa a inactivo si la persona cambia de ciudad.
)
;

CREATE TABLE  cliente_tarjetacredito
(
	K_IDTARJETACREDITO NUMBER(10) NOT NULL,    -- Identificador único de una tarjeta de crédito
	K_IDCLIENTE NUMBER(10) NOT NULL    -- Identificador único del cliente.
)
;

CREATE TABLE  costo_envio
(
	K_IDCOSTOENVIO NUMBER(10) NOT NULL,
	K_IDCIUDADORIGEN NUMBER(10) NOT NULL,    -- K_IDCIUDADORIGEN: Describe la ciudad de la cual se va enviar el pedido.
	K_IDCIUDADDESTINO NUMBER(10) NOT NULL,    -- K_IDCIUDADDESTINO: Describe la ciudad a la cual se va enviar el pedido.
	V_VALOR NUMBER(10) NOT NULL,    -- V_VALOR: Describe el valor generado para el costo de envío, dependiendo de la ciudad seleccionado por el cliente.
	F_FECHA DATE NOT NULL    -- F_FECHA: Describe la fecha en que se calcula el costo de envío
)
;

CREATE TABLE  direccion
(
	K_IDDIRECCION NUMBER(10) NOT NULL,    -- Identificador unico de la direccion de entrega del pedido 
	N_DIRECCION VARCHAR(50) NOT NULL,    -- registro de la direccion de la entrega 
	Q_TELEFONO NUMBER(10) NOT NULL,    -- telefono de contacto asociado al domicilio de la entrega del pedido
	K_IDCIUDAD NUMBER(10) NULL
)
;

CREATE TABLE  inventario
(
	K_IDINVENTARIO NUMBER(10) NOT NULL,    -- identificador del inventario
	V_PRECIO NUMBER(10,2) NOT NULL,    -- precio del producto en pesos colombianos
	Q_CANTIDAD NUMBER(5) NOT NULL,    -- Número de existencias del producto dadas por el proveedor en la fecha especificada
	K_IDREFERENCIAUNICA NUMBER(10) NOT NULL,    -- identificador de referencia
	K_IDCIUDAD NUMBER(10) NOT NULL,    -- Ciudad asociada al producto en el inventario
	K_IDPROVEEDOR NUMBER(10) NULL,    -- Proveedor que suministró el producto
	Q_STOCK NUMBER(5) NOT NULL,    -- Existencias disponibles del producto
	F_FECHAINVENTARIO DATE NOT NULL    -- Fecha en la que se suministró el producto
)
;

CREATE TABLE  pago
(
	K_IDPAGO NUMBER(10) NOT NULL,    -- Identificador único del pago
	F_FECHA DATE NOT NULL,    -- Almacena la fecha en que inicia de proceso de pago
	I_TIPO VARCHAR(20) NOT NULL,    -- Referencia el medio por el cual se hará el pago (pse, tarjeta de crédito)
	Q_VALOR NUMBER(10,2) NOT NULL,    -- Valor a pagar correspondiente al valor total del pedido del cliente
	I_ESTADO VARCHAR(10) NOT NULL,    -- Referencia el estado actual de la transacción (iniciado, en proceso, aprobado, rechazado, cancelado)
	K_IDPEDIDOCLIENTE NUMBER(10) NOT NULL    -- Identificador del pedido del cliente al cual se esta haciendo el pago
)
;

CREATE TABLE  pago_pse
(
	K_IDPAGOPSE NUMBER(10) NOT NULL,    -- Identificador del pago por pse
	N_BANCO VARCHAR(50) NOT NULL,    -- Nombre del banco por el cual se paga
	Q_NUMEROIDENTIFICACION NUMBER(15) NOT NULL,    -- Numero de identificación de la persona que realiza el pago
	O_EMAIL VARCHAR(100) NOT NULL,    -- Correo electrónico de la persona que realiza el pago
	N_NOMBREDUENO VARCHAR(100) NOT NULL,    -- Nombre del titular de la cuenta bancaria
	K_IDPAGO NUMBER(10) NOT NULL    -- Identificador del pago al cual se esta realizando el pago por pse
)
;

CREATE TABLE  pago_tarjetacredito
(
	K_IDPAGO NUMBER(10) NOT NULL,    -- Identificador del pago al cual se esta realizando el pago por tarjeta de crédito
	K_IDTARJETACREDITO NUMBER(10) NOT NULL    -- Identificador de la tarjeta de crédito con la cual se esta realizando el pago
)
;

CREATE TABLE  parametro
(
	K_IDPARAMTERO NUMBER(10) NOT NULL,
	F_FECHA DATE NOT NULL,    -- Fecha en que se establece el parámetro
	N_NOMBRE VARCHAR(50) NOT NULL,    -- Nombre del parámetro
	Q_VALOR NUMBER(5,2) NOT NULL    -- Valor del parámetro
)
;

CREATE TABLE  pedido_cliente
(
	K_IDPEDIDOCLIENTE NUMBER(10) NOT NULL,    -- Identificador único del pedido para un cliente
	F_FECHACREACION DATE NOT NULL,    -- Fecha de creación del pedido del cliente
	F_FECHAMODIFICACION DATE NOT NULL,    -- Última fecha en que se modificaron los productos del pedido
	I_ESTADO VARCHAR(20) NOT NULL,    -- Situación en que se encuentra el pedido, si está enviado, si está en preparación o si ya se ha entregado
	K_IDDIRECCION NUMBER(10) NULL,    -- Dirección de domicilio del cliente
	V_SUBTOTAL NUMBER(10,2) NOT NULL,    -- Costo de los productos del pedido, sin tener en cuenta el costo de envío, impuestos o descuentos si aplica.
	Q_NUMEROPRODUCTOS NUMBER(3) NOT NULL,    -- Cantidad de productos en el pedido del cliente
	F_FECHAENTREGA DATE NULL,    -- Fecha en que el pedido llegó al domicilio de cliente
	K_IDCLIENTE NUMBER(8) NOT NULL,    -- Identificador unico del cliente
	V_COSTOENVIO NUMBER(10,2) NULL,    -- Costo adicional de transporte para garantizar la entrega del pedido al domicilio del cliente
	V_VALORTOTAL NUMBER(10,2) NOT NULL,    -- Costo total del pedido, relacionando costo de los productos, impuestos, envío y descuentos si aplica
	V_IVA NUMBER(10,2) NOT NULL    -- Impuesto de valor agregado
)
;

CREATE TABLE  producto
(
	K_IDREFERENCIAUNICA NUMBER(10) NOT NULL,    -- Numero de referencia que identifica a un producto
	N_NOMBRE VARCHAR(50) NOT NULL,    -- Nombre del producto
	N_MARCA VARCHAR(50) NULL,    -- Marca del producto
	K_IDCATEGORIA NUMBER(10) NOT NULL,    -- Identificador de la categoría a la que pertenece el producto
	N_UNIDADMEDIDA VARCHAR(15) NOT NULL,    -- Nombre de la unidad de medida relacionada con el producto
	L_IMAGEN VARCHAR(50) NULL    -- Dirección de enlace que hace referencia a la imagen del producto
)
;

CREATE TABLE  producto_pedidocliente
(
	K_IDPRODUCTOPEDIDOCLIENTE NUMBER(10) NOT NULL,    -- Identificador único del registro
	K_IDPEDIDOCLIENTE NUMBER(10) NOT NULL,    -- Identificador del pedido del cliente
	K_IDINVENTARIO NUMBER(10) NOT NULL,    -- Referencia del producto en el inventario
	Q_CANTIDAD NUMBER(5,2) NOT NULL,    -- Cantidad del producto
	V_PRECIO NUMBER(10,2) NOT NULL    -- Precio de la cantidad de productos
)
;

CREATE TABLE  proveedor
(
	K_IDPROVEEDOR NUMBER(10) NOT NULL,    -- identificador unico del proveedor
	N_NOMBRE VARCHAR(75) NOT NULL,    -- nombre del proveedor
	N_DIRECCION VARCHAR(50) NOT NULL,    -- direccion del proveedor 
	N_CIUDAD VARCHAR(50) NOT NULL,    -- ciudad del proveedor, diferencia las direcciones donde puede estar el proveedor
	K_IDINVENTARIO NUMBER(10) NULL
)
;

CREATE TABLE  tarjeta_credito
(
	K_IDTARJETACREDITO NUMBER(10) NOT NULL,    -- Identificador unico de la tarjeta de credito
	F_FECHAVENCIMIENTO DATE NOT NULL,    -- fecha de vencimiento asociada a la tarjeta de credito
	Q_NUMEROTARJETA NUMBER(15) NOT NULL,    -- numero personal de la tarjeta de credito asignado por el banco
	N_NOMBREDUENO VARCHAR(100) NOT NULL    -- nombre del dueño asociado a la tarjeta por el banco
)
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON TABLE  categoria IS 'Contiene las categorías y subcategorías sobre las que están clasificados los productos'
;

COMMENT ON COLUMN  categoria.K_IDCATEGORIA IS 'Identificador de la categoría'
;

COMMENT ON COLUMN  categoria.N_NOMBRE IS 'Nombre de la categoría'
;

COMMENT ON COLUMN  categoria.K_IDCATEGORIAPADRE IS 'Identificador de la categoría padre. Usado para especificar que una categoría es una subcategoría de otra'
;

COMMENT ON TABLE  ciudad IS 'Almacena todas las ciudades donde la cadena de tiendas RAFASE posee sucursales'
;

COMMENT ON COLUMN  ciudad.K_IDCIUDAD IS 'Identificador de la ciudad'
;

COMMENT ON COLUMN  ciudad.N_NOMBRE IS 'Nombre de la ciudad'
;

COMMENT ON TABLE  cliente IS 'Contiene la información principal del cliente registrado.'
;

COMMENT ON COLUMN  cliente.K_IDCLIENTE IS 'Respresenta el identificador de cada uno de los clientes registrados en el sistema.'
;

COMMENT ON COLUMN  cliente.I_TIPOIDENT IS 'Tipo de identificación'
;

COMMENT ON COLUMN  cliente.K_NUMIDENT IS 'Número de identificación propio de cada persona DNI'
;

COMMENT ON COLUMN  cliente.N_NOMBRE IS 'Nombre del cliente'
;

COMMENT ON COLUMN  cliente.F_FECHANACIMIENTO IS 'Fecha de nacimiento del cliente, a partir de la cual se calcula su edad'
;

COMMENT ON COLUMN  cliente.I_GENERO IS 'Género con el cual se identifica del cliente'
;

COMMENT ON COLUMN  cliente.O_EMAIL IS 'Correo electrónico perteneciente al cliente y a través del cual se le brindará información de su cuenta'
;

COMMENT ON TABLE  cliente_direccion IS 'Registra la dirección del domicilio de los clientes registrados'
;

COMMENT ON COLUMN  cliente_direccion.K_IDCLIENTE IS 'Número único de identificación del cliente'
;

COMMENT ON COLUMN  cliente_direccion.K_IDDIRECCION IS 'Identificador único de la dirección de domicilio'
;

COMMENT ON COLUMN  cliente_direccion.I_ESTADO IS 'Estado de la dirección del cliente. Activo si está disponible. Inactivo si no lo está. Se pasa a inactivo si la persona cambia de ciudad.'
;

COMMENT ON TABLE  cliente_tarjetacredito IS 'Registra la información de tarjetas de crédito pertenecientes al cliente'
;

COMMENT ON COLUMN  cliente_tarjetacredito.K_IDTARJETACREDITO IS 'Identificador único de una tarjeta de crédito'
;

COMMENT ON COLUMN  cliente_tarjetacredito.K_IDCLIENTE IS 'Identificador único del cliente.'
;

COMMENT ON TABLE  costo_envio IS 'Tabla costo_ envio Representa el costo que se puede generar si al momento de concretarse un pedido, la ciudad de destino no corresponde a la misma ciudad desde la cual se solicito el pedido.'
;

COMMENT ON COLUMN  costo_envio.K_IDCIUDADORIGEN IS 'K_IDCIUDADORIGEN: Describe la ciudad de la cual se va enviar el pedido.'
;

COMMENT ON COLUMN  costo_envio.K_IDCIUDADDESTINO IS 'K_IDCIUDADDESTINO: Describe la ciudad a la cual se va enviar el pedido.'
;

COMMENT ON COLUMN  costo_envio.V_VALOR IS 'V_VALOR: Describe el valor generado para el costo de envío, dependiendo de la ciudad seleccionado por el cliente.'
;

COMMENT ON COLUMN  costo_envio.F_FECHA IS 'F_FECHA: Describe la fecha en que se calcula el costo de envío'
;

COMMENT ON TABLE  direccion IS 'entidad encargada de registrar los domicilios de entrega del usuario '
;

COMMENT ON COLUMN  direccion.K_IDDIRECCION IS 'Identificador unico de la direccion de entrega del pedido '
;

COMMENT ON COLUMN  direccion.N_DIRECCION IS 'registro de la direccion de la entrega '
;

COMMENT ON COLUMN  direccion.Q_TELEFONO IS 'telefono de contacto asociado al domicilio de la entrega del pedido'
;

COMMENT ON TABLE  inventario IS 'Entidad encargada de registrar los pedidos de productos realizados a un proveedor en una ciudad'
;

COMMENT ON COLUMN  inventario.K_IDINVENTARIO IS 'identificador del inventario'
;

COMMENT ON COLUMN  inventario.V_PRECIO IS 'precio del producto en pesos colombianos'
;

COMMENT ON COLUMN  inventario.Q_CANTIDAD IS 'Número de existencias del producto dadas por el proveedor en la fecha especificada'
;

COMMENT ON COLUMN  inventario.K_IDREFERENCIAUNICA IS 'identificador de referencia'
;

COMMENT ON COLUMN  inventario.K_IDCIUDAD IS 'Ciudad asociada al producto en el inventario'
;

COMMENT ON COLUMN  inventario.K_IDPROVEEDOR IS 'Proveedor que suministró el producto'
;

COMMENT ON COLUMN  inventario.Q_STOCK IS 'Existencias disponibles del producto'
;

COMMENT ON COLUMN  inventario.F_FECHAINVENTARIO IS 'Fecha en la que se suministró el producto'
;

COMMENT ON TABLE  pago IS 'Entidad que registra el proceso de pago realizado por el usuario'
;

COMMENT ON COLUMN  pago.K_IDPAGO IS 'Identificador único del pago'
;

COMMENT ON COLUMN  pago.F_FECHA IS 'Almacena la fecha en que inicia de proceso de pago'
;

COMMENT ON COLUMN  pago.I_TIPO IS 'Referencia el medio por el cual se hará el pago (pse, tarjeta de crédito)'
;

COMMENT ON COLUMN  pago.Q_VALOR IS 'Valor a pagar correspondiente al valor total del pedido del cliente'
;

COMMENT ON COLUMN  pago.I_ESTADO IS 'Referencia el estado actual de la transacción (iniciado, en proceso, aprobado, rechazado, cancelado)'
;

COMMENT ON COLUMN  pago.K_IDPEDIDOCLIENTE IS 'Identificador del pedido del cliente al cual se esta haciendo el pago'
;

COMMENT ON TABLE  pago_pse IS 'Registra el pago realizado por el método pse'
;

COMMENT ON COLUMN  pago_pse.K_IDPAGOPSE IS 'Identificador del pago por pse'
;

COMMENT ON COLUMN  pago_pse.N_BANCO IS 'Nombre del banco por el cual se paga'
;

COMMENT ON COLUMN  pago_pse.Q_NUMEROIDENTIFICACION IS 'Numero de identificación de la persona que realiza el pago'
;

COMMENT ON COLUMN  pago_pse.O_EMAIL IS 'Correo electrónico de la persona que realiza el pago'
;

COMMENT ON COLUMN  pago_pse.N_NOMBREDUENO IS 'Nombre del titular de la cuenta bancaria'
;

COMMENT ON COLUMN  pago_pse.K_IDPAGO IS 'Identificador del pago al cual se esta realizando el pago por pse'
;

COMMENT ON TABLE  pago_tarjetacredito IS 'Registra el pago realizado por el método tarjeta de crédito'
;

COMMENT ON COLUMN  pago_tarjetacredito.K_IDPAGO IS 'Identificador del pago al cual se esta realizando el pago por tarjeta de crédito'
;

COMMENT ON COLUMN  pago_tarjetacredito.K_IDTARJETACREDITO IS 'Identificador de la tarjeta de crédito con la cual se esta realizando el pago'
;

COMMENT ON TABLE  parametro IS 'Tabla de parámetros, donde se especifican distintas parametrizaciones del sistema'
;

COMMENT ON COLUMN  parametro.F_FECHA IS 'Fecha en que se establece el parámetro'
;

COMMENT ON COLUMN  parametro.N_NOMBRE IS 'Nombre del parámetro'
;

COMMENT ON COLUMN  parametro.Q_VALOR IS 'Valor del parámetro'
;

COMMENT ON TABLE  pedido_cliente IS 'Relaciona toda la información acerca del pedido del cliente, su dirección, sus prductos, su cantidad, las fechas en que se creó y finalizó el carrito de compras y la fecha en que el pedido fue entregado en el domicilio del cliente'
;

COMMENT ON COLUMN  pedido_cliente.K_IDPEDIDOCLIENTE IS 'Identificador único del pedido para un cliente'
;

COMMENT ON COLUMN  pedido_cliente.F_FECHACREACION IS 'Fecha de creación del pedido del cliente'
;

COMMENT ON COLUMN  pedido_cliente.F_FECHAMODIFICACION IS 'Última fecha en que se modificaron los productos del pedido'
;

COMMENT ON COLUMN  pedido_cliente.I_ESTADO IS 'Situación en que se encuentra el pedido, si está enviado, si está en preparación o si ya se ha entregado'
;

COMMENT ON COLUMN  pedido_cliente.K_IDDIRECCION IS 'Dirección de domicilio del cliente'
;

COMMENT ON COLUMN  pedido_cliente.V_SUBTOTAL IS 'Costo de los productos del pedido, sin tener en cuenta el costo de envío, impuestos o descuentos si aplica.'
;

COMMENT ON COLUMN  pedido_cliente.Q_NUMEROPRODUCTOS IS 'Cantidad de productos en el pedido del cliente'
;

COMMENT ON COLUMN  pedido_cliente.F_FECHAENTREGA IS 'Fecha en que el pedido llegó al domicilio de cliente'
;

COMMENT ON COLUMN  pedido_cliente.K_IDCLIENTE IS 'Identificador unico del cliente'
;

COMMENT ON COLUMN  pedido_cliente.V_COSTOENVIO IS 'Costo adicional de transporte para garantizar la entrega del pedido al domicilio del cliente'
;

COMMENT ON COLUMN  pedido_cliente.V_VALORTOTAL IS 'Costo total del pedido, relacionando costo de los productos, impuestos, envío y descuentos si aplica'
;

COMMENT ON COLUMN  pedido_cliente.V_IVA IS 'Impuesto de valor agregado'
;

COMMENT ON TABLE  producto IS 'Tabla que almacena los productos ofrecidos por la cadena de tiendas'
;

COMMENT ON COLUMN  producto.K_IDREFERENCIAUNICA IS 'Numero de referencia que identifica a un producto'
;

COMMENT ON COLUMN  producto.N_NOMBRE IS 'Nombre del producto'
;

COMMENT ON COLUMN  producto.N_MARCA IS 'Marca del producto'
;

COMMENT ON COLUMN  producto.K_IDCATEGORIA IS 'Identificador de la categoría a la que pertenece el producto'
;

COMMENT ON COLUMN  producto.N_UNIDADMEDIDA IS 'Nombre de la unidad de medida relacionada con el producto'
;

COMMENT ON COLUMN  producto.L_IMAGEN IS 'Dirección de enlace que hace referencia a la imagen del producto'
;

COMMENT ON TABLE  producto_pedidocliente IS 'Registra los productos que desea comprar el usuario'
;

COMMENT ON COLUMN  producto_pedidocliente.K_IDPRODUCTOPEDIDOCLIENTE IS 'Identificador único del registro'
;

COMMENT ON COLUMN  producto_pedidocliente.K_IDPEDIDOCLIENTE IS 'Identificador del pedido del cliente'
;

COMMENT ON COLUMN  producto_pedidocliente.K_IDINVENTARIO IS 'Referencia del producto en el inventario'
;

COMMENT ON COLUMN  producto_pedidocliente.Q_CANTIDAD IS 'Cantidad del producto'
;

COMMENT ON COLUMN  producto_pedidocliente.V_PRECIO IS 'Precio de la cantidad de productos'
;

COMMENT ON TABLE  proveedor IS 'Entidad encargada de registrar los proveedores que suministran productos a la tienda'
;

COMMENT ON COLUMN  proveedor.K_IDPROVEEDOR IS 'identificador unico del proveedor'
;

COMMENT ON COLUMN  proveedor.N_NOMBRE IS 'nombre del proveedor'
;

COMMENT ON COLUMN  proveedor.N_DIRECCION IS 'direccion del proveedor '
;

COMMENT ON COLUMN  proveedor.N_CIUDAD IS 'ciudad del proveedor, diferencia las direcciones donde puede estar el proveedor'
;

COMMENT ON TABLE  tarjeta_credito IS 'entidad que registra las tarjetas de credito del usuario '
;

COMMENT ON COLUMN  tarjeta_credito.K_IDTARJETACREDITO IS 'Identificador unico de la tarjeta de credito'
;

COMMENT ON COLUMN  tarjeta_credito.F_FECHAVENCIMIENTO IS 'fecha de vencimiento asociada a la tarjeta de credito'
;

COMMENT ON COLUMN  tarjeta_credito.Q_NUMEROTARJETA IS 'numero personal de la tarjeta de credito asignado por el banco'
;

COMMENT ON COLUMN  tarjeta_credito.N_NOMBREDUENO IS 'nombre del dueño asociado a la tarjeta por el banco'
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  categoria 
 ADD CONSTRAINT PK_CATEGORIA
	PRIMARY KEY (K_IDCATEGORIA) 
 USING INDEX
;

ALTER TABLE  ciudad 
 ADD CONSTRAINT PK_CIUDAD
	PRIMARY KEY (K_IDCIUDAD) 
 USING INDEX
;

ALTER TABLE  cliente 
 ADD CONSTRAINT PK_CLIENTE
	PRIMARY KEY (K_IDCLIENTE) 
 USING INDEX
;

ALTER TABLE  cliente 
 ADD CONSTRAINT UNQ_CLIENTE_NUMIDENT UNIQUE (K_NUMIDENT) 
 USING INDEX
;

ALTER TABLE  cliente 
 ADD CONSTRAINT UNQ_CLIENTE_OEMAIL UNIQUE (O_EMAIL) 
 USING INDEX
;

ALTER TABLE  cliente 
 ADD CONSTRAINT UNQ_CLIENTE_NNOMBREUSUUARIO UNIQUE (N_NOMBREUSUARIO) 
 USING INDEX
;

ALTER TABLE  cliente 
 ADD CONSTRAINT CK_CIENTE_IGENERO CHECK (I_GENERO IN('M', 'F'))
;

ALTER TABLE  cliente 
 ADD CONSTRAINT CK_CLIENTE_TIPOIDENT CHECK (I_TIPOIDENT IN ('CC','TI','RC','CE','PA'))
;

ALTER TABLE  cliente_direccion 
 ADD CONSTRAINT PK_CLIENTE_DIRECCION
	PRIMARY KEY (K_IDCLIENTE,K_IDDIRECCION) 
 USING INDEX
;

ALTER TABLE  cliente_direccion 
 ADD CONSTRAINT CK_I_ESTADO_CLIENTEDIR CHECK (I_ESTADO IN ('ACTIVO','INACTIVO'))
;

ALTER TABLE  cliente_tarjetacredito 
 ADD CONSTRAINT PK_CLIENTE_TARJETACREDITO
	PRIMARY KEY (K_IDTARJETACREDITO,K_IDCLIENTE) 
 USING INDEX
;

ALTER TABLE  costo_envio 
 ADD CONSTRAINT PK_COSTOENVIO
	PRIMARY KEY (K_IDCOSTOENVIO) 
 USING INDEX
;

ALTER TABLE  costo_envio 
 ADD CONSTRAINT CK_COSTOENVIO_VVALOR CHECK (V_VALOR>=0)
;

ALTER TABLE  direccion 
 ADD CONSTRAINT PK_DIRECCION
	PRIMARY KEY (K_IDDIRECCION) 
 USING INDEX
;

ALTER TABLE  direccion 
 ADD CONSTRAINT CK_DIRECCION_QTELEFONO CHECK (Q_TELEFONO>=0)
;

ALTER TABLE  inventario 
 ADD CONSTRAINT PK_INVENTARIO
	PRIMARY KEY (K_IDINVENTARIO) 
 USING INDEX
;

ALTER TABLE  inventario 
 ADD CONSTRAINT CK_INVENTARIO_VPRECIO CHECK (V_PRECIO >=0)
;

ALTER TABLE  inventario 
 ADD CONSTRAINT CK_INVENTARIO_QCANTIDAD CHECK (Q_CANTIDAD>=0)
;

ALTER TABLE  inventario 
 ADD CONSTRAINT Q_STOCK CHECK (Q_STOCK >= 0 and Q_STOCK <= Q_CANTIDAD)
;

ALTER TABLE  pago 
 ADD CONSTRAINT PK_PAGO
	PRIMARY KEY (K_IDPAGO) 
 USING INDEX
;

ALTER TABLE  pago 
 ADD CONSTRAINT CK_PAGO_IESTADOPAGO CHECK (I_ESTADO IN('INICIADO', 'EN PROCESO', 'APROBADO', 'RECHAZADO', 'CANCELADO'))
;

ALTER TABLE  pago 
 ADD CONSTRAINT CK_PAGO_ITIPOPAGO CHECK (I_TIPO IN ('PSE', 'TARJETA DE CREDITO'))
;

ALTER TABLE  pago 
 ADD CONSTRAINT CK_PAGO_QVALOR CHECK (Q_VALOR > 0)
;

ALTER TABLE  pago_pse 
 ADD CONSTRAINT PK_PAGOPSE
	PRIMARY KEY (K_IDPAGOPSE) 
 USING INDEX
;

ALTER TABLE  pago_tarjetacredito 
 ADD CONSTRAINT PK_PAGOTARJETACREDITO
	PRIMARY KEY (K_IDPAGO,K_IDTARJETACREDITO) 
 USING INDEX
;

ALTER TABLE  parametro 
 ADD CONSTRAINT PK_PARAMTERO
	PRIMARY KEY (K_IDPARAMTERO) 
 USING INDEX
;

ALTER TABLE  parametro 
 ADD CONSTRAINT CK_PRM_QVALOR CHECK (Q_VALOR>0)
;

ALTER TABLE  pedido_cliente 
 ADD CONSTRAINT PK_PEDIDOCLIENTE
	PRIMARY KEY (K_IDPEDIDOCLIENTE) 
 USING INDEX
;

ALTER TABLE  pedido_cliente 
 ADD CONSTRAINT CK_PEDCLI_IESTADO CHECK (I_ESTADO IN('INICIADO', 'PAGANDO', 'PAGADO', 'CANCELADO', 'DESPACHANDO', 'ENVIADO'))
;

ALTER TABLE  pedido_cliente 
 ADD CONSTRAINT CK_PEDCLI_VSUBTOTAL CHECK (V_SUBTOTAL >= 0)
;

ALTER TABLE  pedido_cliente 
 ADD CONSTRAINT CK_PEDCLI_NUMEROPRODUCTOS CHECK (Q_NUMEROPRODUCTOS >=0)
;

ALTER TABLE  pedido_cliente 
 ADD CONSTRAINT CK_PEDCLI_VVALORTOTAL CHECK (V_VALORTOTAL >=0)
;

ALTER TABLE  pedido_cliente 
 ADD CONSTRAINT CK_PEDCLI_VCOSTOENVIO CHECK (V_COSTOENVIO >= 0)
;

ALTER TABLE  producto 
 ADD CONSTRAINT PK_REFERENCIAUNICA
	PRIMARY KEY (K_IDREFERENCIAUNICA) 
 USING INDEX
;

ALTER TABLE  producto_pedidocliente 
 ADD CONSTRAINT PK_PRODUCTOPEDIDOCLIENTE
	PRIMARY KEY (K_IDPRODUCTOPEDIDOCLIENTE) 
 USING INDEX
;

ALTER TABLE  producto_pedidocliente 
 ADD CONSTRAINT CK_PRODPEDCLI_VPRECIO CHECK (V_PRECIO > 0)
;

ALTER TABLE  producto_pedidocliente 
 ADD CONSTRAINT CK_PRODPEDCLI_QCANTIDAD CHECK (Q_CANTIDAD > 0)
;

ALTER TABLE  proveedor 
 ADD CONSTRAINT PK_PROVEEDOR
	PRIMARY KEY (K_IDPROVEEDOR) 
 USING INDEX
;

ALTER TABLE  tarjeta_credito 
 ADD CONSTRAINT PK_TARJETACREDITO
	PRIMARY KEY (K_IDTARJETACREDITO) 
 USING INDEX
;

ALTER TABLE  tarjeta_credito 
 ADD CONSTRAINT CK_QNUMEROTARJETA CHECK (Q_NUMEROTARJETA>=0)
;

/* Create Foreign Key Constraints */

ALTER TABLE  categoria 
 ADD CONSTRAINT FK_CATEGORIA_CATEGORIAPADRE
	FOREIGN KEY (K_IDCATEGORIAPADRE) REFERENCES  categoria (K_IDCATEGORIA)
;

ALTER TABLE  cliente 
 ADD CONSTRAINT FK_cliente_ciudad
	FOREIGN KEY (K_IDCIUDAD) REFERENCES  ciudad (K_IDCIUDAD)
;

ALTER TABLE  cliente_direccion 
 ADD CONSTRAINT FK_CLIENTEDIRECCION_CLIENTE
	FOREIGN KEY (K_IDCLIENTE) REFERENCES  cliente (K_IDCLIENTE)
;

ALTER TABLE  cliente_tarjetacredito 
 ADD CONSTRAINT FK_CLIENTETARJETA_CLIENTE
	FOREIGN KEY (K_IDCLIENTE) REFERENCES  cliente (K_IDCLIENTE)
;

ALTER TABLE  cliente_tarjetacredito 
 ADD CONSTRAINT FK_CLITARJETA_TARJETA
	FOREIGN KEY (K_IDTARJETACREDITO) REFERENCES  tarjeta_credito (K_IDTARJETACREDITO)
;

ALTER TABLE  costo_envio 
 ADD CONSTRAINT FK_COSTOENVIO_CIUDADDESTINO
	FOREIGN KEY (K_IDCIUDADDESTINO) REFERENCES  ciudad (K_IDCIUDAD)
;

ALTER TABLE  costo_envio 
 ADD CONSTRAINT FK_COSTOENVIO_CIUDADORIGEN
	FOREIGN KEY (K_IDCIUDADORIGEN) REFERENCES  ciudad (K_IDCIUDAD)
;

ALTER TABLE  direccion 
 ADD CONSTRAINT FK_direccion_ciudad
	FOREIGN KEY (K_IDCIUDAD) REFERENCES  ciudad (K_IDCIUDAD)
;

ALTER TABLE  inventario 
 ADD CONSTRAINT FK_INVENTARIO_CIUDAD
	FOREIGN KEY (K_IDCIUDAD) REFERENCES  ciudad (K_IDCIUDAD)
;

ALTER TABLE  inventario 
 ADD CONSTRAINT FK_INVENTARIO_PRODUCTO
	FOREIGN KEY (K_IDREFERENCIAUNICA) REFERENCES  producto (K_IDREFERENCIAUNICA)
;

ALTER TABLE  inventario 
 ADD CONSTRAINT FK_inventario_proveedor
	FOREIGN KEY (K_IDPROVEEDOR) REFERENCES  proveedor (K_IDPROVEEDOR)
;

ALTER TABLE  pago 
 ADD CONSTRAINT FK_PAGO_PEDIDOCLIENTE
	FOREIGN KEY (K_IDPEDIDOCLIENTE) REFERENCES  pedido_cliente (K_IDPEDIDOCLIENTE)
;

ALTER TABLE  pago_pse 
 ADD CONSTRAINT FK_PAGOPSE_PAGO
	FOREIGN KEY (K_IDPAGO) REFERENCES  pago (K_IDPAGO)
;

ALTER TABLE  pago_tarjetacredito 
 ADD CONSTRAINT FK_PAGOTARJETA_PAGO
	FOREIGN KEY (K_IDPAGO) REFERENCES  pago (K_IDPAGO)
;

ALTER TABLE  pago_tarjetacredito 
 ADD CONSTRAINT FK_PAGOTARJETA_TARJETA
	FOREIGN KEY (K_IDTARJETACREDITO) REFERENCES  tarjeta_credito (K_IDTARJETACREDITO)
;

ALTER TABLE  pedido_cliente 
 ADD CONSTRAINT FK_pedidoclien_cliente_dir
	FOREIGN KEY (K_IDCLIENTE,K_IDDIRECCION) REFERENCES  cliente_direccion (K_IDCLIENTE,K_IDDIRECCION)
;

ALTER TABLE  producto 
 ADD CONSTRAINT FK_PRODUCTO_CATEGORIA
	FOREIGN KEY (K_IDCATEGORIA) REFERENCES  categoria (K_IDCATEGORIA)
;

ALTER TABLE  producto_pedidocliente 
 ADD CONSTRAINT FK_PRODPEDCLI_INVENTARIO
	FOREIGN KEY (K_IDINVENTARIO) REFERENCES  inventario (K_IDINVENTARIO)
;

ALTER TABLE  producto_pedidocliente 
 ADD CONSTRAINT FK_PRODPEDCLI_PEDCLI
	FOREIGN KEY (K_IDPEDIDOCLIENTE) REFERENCES  pedido_cliente (K_IDPEDIDOCLIENTE)
;
