
/* Drop Triggers, Sequences for Autonumber Columns */

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_categoria_K_IDCATEGORIA'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_categoria_K_IDCATEGORIA'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_categoria_K_IDCATEGORIA'; 
  IF (C >= 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_categoria_K_IDCATEGORIA'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_ciudad_K_IDCIUDAD'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ciudad_K_IDCIUDAD'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_ciudad_K_IDCIUDAD'; 
  IF (C >= 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ciudad_K_IDCIUDAD'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_cliente_K_IDCLIENTE'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_cliente_K_IDCLIENTE'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_cliente_K_IDCLIENTE'; 
  IF (C >= 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_cliente_K_IDCLIENTE'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_costo_envio_K_IDCOSTOENVIO'; 
  IF (C >= 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_costo_envio_K_IDCOSTOENVIO'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_costo_envio_K_IDCOSTOENVIO'; 
  IF (C >= 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_costo_envio_K_IDCOSTOENVIO'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_direccion_K_IDDIRECCION'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_direccion_K_IDDIRECCION'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_direccion_K_IDDIRECCION'; 
  IF (C >= 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_direccion_K_IDDIRECCION'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_inventario_K_IDINVENTARIO'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_inventario_K_IDINVENTARIO'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_inventario_K_IDINVENTARIO'; 
  IF (C >= 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_inventario_K_IDINVENTARIO'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_log_K_IDLOG'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_log_K_IDLOG'; 
END IF; 
END; 
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_log_K_IDLOG'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_log_K_IDLOG'; 
END IF; 
END; 
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_pago_K_IDPAGO'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_pago_K_IDPAGO'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_pago_K_IDPAGO'; 
  IF (C >= 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_pago_K_IDPAGO'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_pago_pse_K_IDPAGOPSE'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_pago_pse_K_IDPAGOPSE'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_pago_pse_K_IDPAGOPSE'; 
  IF (C >= 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_pago_pse_K_IDPAGOPSE'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_parametro_KIDPARAMTERO'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_parametro_KIDPARAMTERO'; 
END IF; 
END; 
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_parametro_KIDPARAMTERO'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_parametro_KIDPARAMTERO'; 
END IF; 
END; 
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_ped_cli_KIDPEDIDOCLIENTE'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ped_cli_KIDPEDIDOCLIENTE'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_ped_cli_KIDPEDIDOCLIENTE'; 
  IF (C >= 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ped_cli_KIDPEDIDOCLIENTE'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_prod_pedcli_KIDPRODPEDCLI'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_prod_pedcli_KIDPRODPEDCLI'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_prod_pedcli_KIDPRODPEDCLI'; 
  IF (C >= 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_prod_pedcli_KIDPRODPEDCLI'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_proveedor_K_IDPROVEEDOR'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_proveedor_K_IDPROVEEDOR'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_proveedor_K_IDPROVEEDOR'; 
  IF (C >= 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_proveedor_K_IDPROVEEDOR'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_tar_cred_KIDTARJETACREDITO'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_tar_cred_KIDTARJETACREDITO'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_tar_cred_KIDTARJETACREDITO'; 
  IF (C >= 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_tar_cred_KIDTARJETACREDITO'; 
END IF; 
END;
/

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   categoria CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   ciudad CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   cliente CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   cliente_direccion CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   cliente_tarjetacredito CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   costo_envio CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   direccion CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   inventario CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   inventario_proveedor CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   log CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   pago CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   pago_pse CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   pago_tarjetacredito CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   parametro CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   pedido_cliente CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   producto CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   producto_pedidocliente CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   proveedor CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   tarjeta_credito CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Drop Syninyms */

DROP PUBLIC SYNONYM cli;
DROP PUBLIC SYNONYM ctg;
DROP PUBLIC SYNONYM ciu;
DROP PUBLIC SYNONYM clidir;
DROP PUBLIC SYNONYM clitar;
DROP PUBLIC SYNONYM costoe;
DROP PUBLIC SYNONYM dir;
DROP PUBLIC SYNONYM inv;
DROP PUBLIC SYNONYM invprov;
DROP PUBLIC SYNONYM pg;
DROP PUBLIC SYNONYM pgpse;
DROP PUBLIC SYNONYM pgtar;
DROP PUBLIC SYNONYM prm;
DROP PUBLIC SYNONYM pcli;
DROP PUBLIC SYNONYM prod;
DROP PUBLIC SYNONYM prodpcli;
DROP PUBLIC SYNONYM prov;
DROP PUBLIC SYNONYM tar;

/* Drop users and roles */

DROP USER clisrrfs CASCADE;
DROP ROLE clirrfs;
DROP USER useradmrfs CASCADE;
DROP ROLE admrfs;
DROP USER admusrrfs CASCADE;
DROP USER dbarfs CASCADE;


/* Drop TableSpace's */

DROP TABLESPACE rfstmp;
DROP TABLESPACE rfsdef;

DROP TABLESPACE rfsdbatmp;
DROP TABLESPACE rfsdbadef;


